#include "main.h"

BSDATA(abilityi) = {
	{"LineOfSight"},
	{"Brawl"},
	{"Dexterity"},
	{"Wits"},
	{"Charisma"},
	{"WeaponSkill", Brawl},
	{"BalisticSkill", Dexterity},
	{"DodgeSkill", Dexterity},
	{"ShieldUse", Dexterity},
	{"Damage"},
	{"DamageMelee"},
	{"DamageRanged"},
	{"DamageThrown"},
	{"ParryValue"},
	{"DamageReduciton"},
	{"Speed"},
	{"Concentration"},
	{"Healing"},
	{"Pickpockets"},
	{"Stealth"},
	{"OpenLocks"},
	{"DisarmTraps"},
	{"Survival"},
	{"Level"},
	{"HitsMaximum"},
	{"ManaMaximum"},
	{"Hits"},
	{"Mana"},
	{"Mood"},
	{"Alignment"},
	{"ParryCount"},
	{"Money"},
};
assert_enum(abilityi, Money)
