#include "main.h"

BSDATA(feati) = {
	{"EnergyDrain"},
	{"Paralysis"},
	{"PetrifyingGaze"},
	{"PoisonImmunity"},
	{"StrenghtDrain"},
	{"SunSensitive"},
	{"Slow"},
	{"NormalWeaponImmunity"},
	{"FireResistance"},
	{"Blunt"},
	{"Martial"},
	{"TwoHanded"},
	{"CutWoods"},
	{"WearLeather"},
	{"WearIron"},
	{"WearLarge"},
	{"WearShield"},
	{"Coins"},
	{"Female"},
	{"Undead"},
	{"Summoned"},
	{"Ally"},
	{"Enemy"},
	{"Stun"},
	{"Unaware"},
};
assert_enum(feati, Unaware)