#include "crt.h"
#include "feat.h"

BSDATA(feati) = {
	{"Darkvision"},
	{"TwoHanded"},
	{"CutWoods"},
	{"Retaliate"},
	{"Thrown"},
	{"StunningHit"},
	{"PierceHit"},
	{"MightyHit"},
	{"IgnoreWeb"},
	{"Fly"},
	{"LightSource"},
	{"Regeneration"},
	{"ManaRegeneration"},
	{"WeakPoison"},
	{"StrongPoison"},
	{"DeathPoison"},
	{"PoisonResistance"},
	{"PoisonImmunity"},
	{"AcidResistance"},
	{"AcidImmunity"},
	{"DiseaseResist"},
	{"DiseaseImmunity"},
	{"Coins"},
	{"Notable"},
	{"Natural"},
	{"KnowRumor"},
	{"KnowLocation"},
	{"Female"},
	{"PlaceOwner"},
	{"Undead"},
	{"Summoned"},
	{"Local"},
	{"Ally"},
	{"Enemy"},
	{"Stun"},
	{"Blooding"},
};
assert_enum(feati, Blooding)