#include "crt.h"
#include "feat.h"

BSDATA(feati) = {
	{"Darkvision"},
	{"TwoHanded"},
	{"CutWoods"},
	{"CutMines"},
	{"Retaliate"},
	{"Thrown"},
	{"BleedingHit"},
	{"StunningHit"},
	{"PierceHit"},
	{"MightyHit"},
	{"MissHalfTime"},
	{"Vorpal"},
	{"FireDamage"},
	{"ColdDamage"},
	{"IgnoreWeb"},
	{"Fly"},
	{"LightSource"},
	{"Regeneration"},
	{"ManaRegeneration"},
	{"WeakPoison"},
	{"StrongPoison"},
	{"DeathPoison"},
	{"PoisonResistance"},
	{"PoisonImmunity"},
	{"AcidResistance"},
	{"AcidImmunity"},
	{"ColdResistance"},
	{"ColdImmunity"},
	{"DeathResistance"},
	{"DeathImmunity"},
	{"DiseaseResist"},
	{"DiseaseImmunity"},
	{"FireResistance"},
	{"FireImmunity"},
	{"StunResistance"},
	{"StunImmunity"},
	{"Coins"},
	{"Notable"},
	{"Natural"},
	{"KnowRumor"},
	{"KnowLocation"},
	{"Female"},
	{"PlaceOwner"},
	{"Undead"},
	{"Summoned"},
	{"Local"},
	{"Ally"},
	{"Enemy"},
	{"Stun"},
	{"Blooding"},
};
assert_enum(feati, Blooding)