#include "main.h"

BSDATA(weari) = {
	{"Backpack"},
	{"Potion"},
	{"Backpack2"},
	{"Backpack3"},
	{"Backpack4"},
	{"Backpack5"},
	{"Backpack6"},
	{"Backpack7"},
	{"Backpack8"},
	{"Backpack9"},
	{"Backpack10"},
	{"Backpack11"},
	{"Backpack12"},
	{"Backpack13"},
	{"Backpack14"},
	{"BackpackLast"},
	{"MeleeWeapon", WeaponSkill},
	{"MeleeWeaponOffhand", WeaponSkill},
	{"RangedWeapon", RangedWeaponSkill},
	{"ThrownWeapon", WeaponSkill},
	{"Ammunition", RangedWeaponSkill},
	{"Head", ParryValue},
	{"Torso", ParryValue},
	{"Backward", ParryValue},
	{"Legs", ParryValue},
	{"Gloves", ParryValue},
	{"FingerRight"},
	{"FingerLeft"},
	{"Elbows", ParryValue},
};
assert_enum(weari, Elbows)